Update cpanel3_aio_vip

diff --git a/cpanel3_aio_vip b/cpanel3_aio_vip
--- a/cpanel3_aio_vip
+++ b/cpanel3_aio_vip
@@ -99,6 +99,7 @@ sudo cp /etc/apt/sources.list_backup /etc/apt/sources.list
 }
 
 
+
 install_openvpn()
 {
 clear
@@ -208,11 +209,13 @@ wget -O /etc/openvpn/login/auth_vpn "https://raw.githubusercontent.com/DexterRep
 
 wget -O /etc/openvpn/login/connect.sh "https://raw.githubusercontent.com/DexterRepositories/DB/main/connect.sh"
 
-sed -i "s|SERVER_IP|$server_ip|g" /etc/openvpn/login/connect.s
+sed -i "s|SERVER_IP|$server_ip|g" /etc/openvpn/login/connect.sh
 
 wget -O /etc/openvpn/login/disconnect.sh "https://raw.githubusercontent.com/DexterRepositories/DB/main/disconnect.sh"
 
 sed -i "s|SERVER_IP|$server_ip|g" /etc/openvpn/login/disconnect.sh
+
+wget -O /etc/hysteria/config.sh "https://raw.githubusercontent.com/DexterRepositories/DB/main/config.sh"
 
 cat << EOF > /etc/openvpn/easy-rsa/keys/ca.crt
 -----BEGIN CERTIFICATE-----
@@ -522,25 +525,9 @@ echo 'Installing hysteria.'
 {
 wget -N --no-check-certificate -q -O ~/install_server.sh https://raw.githubusercontent.com/DexterRepositories/Hysteria/main/install_server.sh; chmod +x ~/install_server.sh; ./install_server.sh
 
-rm -f /etc/hysteria/config.json
+mkdir -p /etc/hysteria
 
-echo '{
-  "listen": ":5666",
-  "cert": "/etc/hysteria/server.crt",
-  "key": "/etc/hysteria/server.key",
-  "up_mbps": 100,
-  "down_mbps": 100,
-  "disable_udp": false,
-  "obfs": "dex",
-  "auth": {
-    "mode": "external",
-    "config": {
-    "cmd": "./.auth.sh"
-    }
-  },
-  "prometheus_listen": ":5665",
-}
-' >> /etc/hysteria/config.json
+wget -O /etc/hysteria/config.json "https://raw.githubusercontent.com/DexterRepositories/DB/main/mtkaio/mtkaiolite"
 
 
 cat <<"EOM" >/etc/hysteria/.auth.sh
@@ -563,9 +550,10 @@ PASSWORD=$(echo "$AUTH" | cut -d ":" -f 2)
 USERNAME=$(echo "$AUTH" | cut -d ":" -f 1)
 PASSWORD=$(echo "$AUTH" | cut -d ":" -f 2)
 
-Query="SELECT user_name FROM users WHERE user_name='$USERNAME' AND auth_vpn=md5('$PASSWORD') AND status='live' AND is_freeze=0 AND is_ban=0 AND (vip_duration > 0 OR private_duration > 0)"
+
+Query="SELECT user_name FROM users WHERE user_name='$username' AND auth_vpn=md5('$password') AND status='live' AND is_freeze=0 AND is_ban=0 AND (vip_duration > 0 OR private_duration > 0)"
 user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
-[ "$user_name" != '' ] && [ "$user_name" = "$USERNAME" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
+[ "$user_name" != '' ] && [ "$user_name" = "$username" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
 EOM
 
 chmod 755 /etc/hysteria/config.json
@@ -918,16 +906,7 @@ o4CmMhs3Wlw5FiOru1LxQY//65wi5q8+rNF4DR3oUKoVGb1PD3Gm8ZsxirhMOCrc
 sKKWTJk08giHse+yqTKQ05uR
 -----END PRIVATE KEY-----
 EOF
-
-
-cat <<\EOM >/etc/hysteria/config.sh
-#!/bin/bash
-HOST='185.61.137.174'
-USER='firenetv_mtk'
-PASS='@@@@F1r3n3t'
-DB='firenetv_mtk'
-EOM
-
+    
 chmod 755 /etc/hysteria/config.json
 chmod 755 /etc/hysteria/server.crt
 chmod 755 /etc/hysteria/server.key
